# Generated by Django 3.0.7 on 2021-03-11 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listings',
        ),
        migrations.AlterField(
            model_name='review',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_listing', to='servapp.Listing'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('rate', models.CharField(max_length=300)),
                ('times', models.TextField()),
                ('days', models.TextField()),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_listing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
