# Generated by Django 3.0.7 on 2021-03-11 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0002_auto_20210311_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_listing', to='servapp.Listing'),
        ),
    ]
