# Generated by Django 3.1.7 on 2021-04-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0002_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='body',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='review',
            name='header',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
