# Generated by Django 3.1.7 on 2021-08-13 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0003_auto_20210424_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing_type',
            new_name='category',
        ),
    ]
