# Generated by Django 3.0.7 on 2020-12-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0003_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(default=False, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(default=False, max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=False, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=False, max_length=300),
        ),
    ]
