# Generated by Django 3.0.7 on 2020-12-15 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0004_auto_20201213_0315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
    ]
