# Generated by Django 3.0.7 on 2021-03-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0004_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
