# Generated by Django 3.0.7 on 2021-03-26 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0006_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='days',
        ),
    ]
