# Generated by Django 3.0.7 on 2021-01-04 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='listing',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='writer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='owner',
            new_name='user',
        ),
    ]
