# Generated by Django 3.0.7 on 2021-01-17 02:28

from django.db import migrations

# example function
# def create_data(apps, schema_editor):
#     Customer = apps.get_model('customers', 'Customer')
#     Customer(first_name="Customer 001", last_name="Customer 001", email="customer001@email.com", phone="00000000", address="Customer 000 Address", description= "Customer 001 description").save()


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0009_review_timestamp'),
    ]

    operations = [
        # example
        # migrations.RunPython(create_data),
    ]

    
