# Generated by Django 3.0.7 on 2021-03-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0010_auto_20210303_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_type',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_service',
            field=models.TextField(default=False, max_length=300),
        ),
        migrations.AddField(
            model_name='service',
            name='services',
            field=models.TextField(blank=True),
        ),
    ]
