# Generated by Django 3.0.7 on 2021-01-18 20:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0010_servapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=900913),
        ),
    ]
