# Generated by Django 3.0.7 on 2021-01-18 22:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servapp', '0011_auto_20210118_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
